export const homeLink = [
  { name: "FAQ", url: "#" },
  { name: "Help Center", url: "#" },
  { name: "Account", url: "#" },
  { name: "Media Center", url: "#" },
  { name: "Investor Relations", url: "#" },
  { name: "Jobs", url: "#" },
  { name: "Redeem Gift Cards", url: "#" },
  { name: "Buy Gift Cards", url: "#" },
  { name: "Ways to Watch", url: "#" },
  { name: "Terms of Use", url: "#" },
  { name: "Privacy", url: "#" },
  { name: "Cookie Preference", url: "#" },
  { name: "Corporate Information", url: "#" },
  { name: "Contact Us", url: "#" },
  { name: "Speed Test", url: "#" },
  { name: "Legal Guarantee", url: "#" },
  { name: "Legal Notices", url: "#" },
  { name: "Only on Netflix", url: "#" },
];
